name: Auto Assign Reviewers

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write  # ✅ Grants permission to request reviewers

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Extract Reviewers from CODEOWNERS
        run: bash .github/scripts/extract_reviewers.sh

      - name: Assign Reviewers
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  # ✅ No need to manually add to secrets
          script: |
            const fs = require('fs');
            const reviewers = fs.readFileSync('.github/reviewers.txt', 'utf-8')
              .split('\n')
              .filter(Boolean);

            if (reviewers.length < 2) {
              throw new Error("❌ At least 2 reviewers are required, but found " + reviewers.length);
            }

            github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: reviewers
            });
